language: php

php:
  - '8.2'
  - '8.3'
  - '8.4'

sudo: false

before_install:
  - travis_retry composer self-update
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable

script: vendor/bin/phpcs --standard=PSR2 src && vendor/bin/phpunit

after_script:
  - mv tests/_reports/logs/clover.xml clover.xml
  - ./cc-test-reporter after-build --coverage-input-type clover --id $CC_TEST_REPORTER_ID --exit-code $TRAVIS_TEST_RESULT
